# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cGocypjYYrMjVa-o_51K0UgQ5Dd0p94D
"""
"""Install the following packages
!pip install nltk
!pip install newspaper3k
"""

#Import the libraries

import nltk
import newspaper

#Get the url
url="https://www.reuters.com/places/india"

reuters = newspaper.build(url, memoize_articles=False)

#NLP
reuters.download()
reuters.parse()
nltk.download('punkt')
#reuters.nlp()

for article in reuters.articles[5:10]:
    print(article.url)

#Extracting Articles
for article in reuters.articles:
    print(article.url)

print(reuters.size())

#Extracting Source Categories

for category in reuters.category_urls():
    print(category)


#Checking the import for the first article

first_article = reuters.articles[0]
#first_article.download()
print(first_article.url)
first_article.download()
first_article.parse()

#current_date: process date

from datetime import datetime
def current_date(first_article):
  now = datetime.now() # current date and time
  date = now.strftime("%m/%d/%Y")
  return date

#story_date and story_time
from datetime import datetime
def date_time(first_article):
  story_date_time = first_article.publish_date
  story_date = story_date_time.strftime("%m/%d/%Y")
  story_time = story_date_time.strftime("%H:%M:%S")
  return story_date, story_time

#author
def author(first_article):
  author = first_article.authors
  return author

#text_in_story
def text(first_article):
  text = first_article.text
  return text
#print(text)

#title
def title(first_article):
  title = first_article.title
  return title
#print(title)

#source
def source(first_article):
  source = first_article.url
  return source

import json
with open('/content/drive/My Drive/Colab Notebooks/Intellimind/store.json', 'w') as f:
  for article in reuters.articles:
    try:
      article.download()
      article.parse()
      story={}
      story["author"] = author(article)
      story["current_date"] = current_date(article)
      st_1, st_2 = date_time(article)
      story["story_date"],story['story_time'] = st_1,st_2
      story["text"] = text(article)
      story["title"] = title(article)
      story["source"] = source(article)
  
      json.dump(story, f, indent=2, ensure_ascii=False)
    except ArticleException:
      pass
    except AttributeError:
      pass

"""----END OF CODE-----"""